### ISSUE TITLE
Cannot run the release

### ISSUE THREAD

**Issue by dzenanz** [gabysbrain/tuner#24]
C:\PETCT-Phantom\Tuner-0.10.2>bin\tuner.bat
Exception in thread "main" java.lang.ExceptionInInitializerError
        at tuner.Tuner.main(Tuner.scala)
Caused by: java.io.FileNotFoundException: C:\Users\Dzenan\C:\Users\Dzenan\AppDat
a\Roaming\UniVie Software\Tuner\prefs.json (The filename, directory name, or vol
ume label syntax is incorrect)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileWriter.<init>(Unknown Source)
        at tuner.Tuner$.savePrefs(Tuner.scala:51)
        at tuner.Tuner$.liftedTree1$1(Tuner.scala:66)
        at tuner.Tuner$.<init>(Tuner.scala:57)
        at tuner.Tuner$.<clinit>(Tuner.scala)
        ... 1 more

C:\PETCT-Phantom\Tuner-0.10.2>

**Comment by gabysbrain** [comment]
Hmm, it looks like the config file isn't get created for some reason. I'll have to find a windows machine and see what's going on.

**Comment by dzenanz** [comment]
The path looks suspicious too (C:\Users\Dzenan\C:\Users\Dzenan\AppDat
a\Roaming\UniVie Software\Tuner\prefs.json), with user directory repeated twice.

**Comment by gabysbrain** [comment]
True. I wonder if it's something to do with the way your profile is set up. Tuner is looking for your APPDATA folder to store preferences. Supposedly APPDATA just points to one folder. Do you know if your profile is set up that way for a reason?

**Comment by dzenanz** [comment]
%appdata% evaluates to C:\Users\Dzenan\AppData\Roaming
There should be nothing special about the way my user is set up. The only thing which is not 100% standard is that I used migration wizard to set up this computer (copying settings and files from the old computer).
